# Site Settings
title: Yeok Soon Goh's Portfolio
description: Personal site powered by Jekyll | Showcasing projects, blog, and resume
url: "https://spottedwoodowl.github.io"    # Your GitHub Pages domain
baseurl: "/ysgoh.github.io"               # Must match your repo name

# Jekyll Configuration
theme: minima  # Using the standard minima theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # For better search engine visibility

# Author Info (for SEO & footer)
author:
  name: Yeok Soon Goh
  email: ysgoh2000@yahoo.com  # Optional


# Defaults (for posts/pages)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Yeok Soon Goh
      show_author: true

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
